framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed
        serializer:
            default_serializer: json_message_serializer
            symfony_serializer:
                format: json
                context: { }

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'
            amqp:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: json_message_serializer
                retry_strategy:
                    max_retries: 5
                    multiplier: 2

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
            'Voucher\MessageHandler\OrderEventHandler':
                senders: [ amqp ]
